:default:
  :name:
    - name **list
:person:
  :name:
    - given_name
    - family_name
    - member_of
:place:
  :name:
    - name
    - - address
      - properties
      - street_address
    - - address
      - properties
      - postal_code
    - - address
      - properties
      - address_locality
:bild:
  :title:
    - name **list
    - caption
    - description
    - tags
  :copyright:
    - copyright_holder **list
    - author **list
    - validity_period
:video:
  :title:
    - name **list
    - caption
    - description
    - tags
  :copyright:
    - copyright_holder **list
    - validity_period
