- Inhaltstypen | filter:
    - $$Asset:
        - $$Audio
        - $$Bild
        - $$Video
    - $$Ort:
        - $$Lift
        - $$Örtlichkeit
        - $$Piste
        - $$POI
        - $$Tour
        - $$Unterkunft
        - $$LocalBusiness
        - $$Gastronomischer Betrieb
    - $$Text:
        - $$Artikel
        - $$Beschreibungstext
        - $$Katalog
    - $$Organisation
    - $$Person
    - $$Pauschalangebot
    - $$Produkte:
        - $$Produkt
        - $$Produktgruppe
        - $$Produktmodel
    - $$Service
    - $$Veranstaltung
    - $$Veranstaltungsserie
    - $$Zimmer
    # embedded
    - $$Veranstaltungstermin
    - $$Öffnungszeit
    - $$Öffnungszeit - Simple
    - $$Öffnungszeit - Zeitspanne
    - $$Overlay
    - $$Publikations-Plan
    - $$EventSchedule

- Geschlecht | all:
    - Männlich | Male **https://schema.org/Male
    - Weiblich | Female **https://schema.org/Female

- Wochentage | all:
    - Montag **https://schema.org/Monday
    - Dienstag **https://schema.org/Tuesday
    - Mittwoch **https://schema.org/Wednesday
    - Donnerstag **https://schema.org/Thursday
    - Freitag **https://schema.org/Friday
    - Samstag **https://schema.org/Saturday
    - Sonntag **https://schema.org/Sunday

- Monate | all:
    - Januar
    - Februar
    - März
    - April
    - Mai
    - Juni
    - Juli
    - August
    - September
    - Oktober
    - November
    - Dezember

- Tags | all:
    - Tag 1
    - Tag 2

- Ausgabekanäle | all:
    - Web
    - Print
    - Social Media

- Beschreibungsarten | all:

- Informationstypen | all:

- $$Externe Informationstypen | all:
    - description | OutdoorActive/imx_platform/TIMM4
    - description_long | imx_platform
    - text | OutdoorActive
    - directions | OutdoorActive
    - directions_public_transport | OutdoorActive
    - parking | OutdoorActive
    - hours_available | OutdoorActive
    - price | OutdoorActive
    - instructions | OutdoorActive
    - safety_instructions | OutdoorActive
    - equipment | OutdoorActive
    - suggestion | OutdoorActive
    - additional_information | OutdoorActive
    - maps | OutdoorActive
    - AdditionalService | Feratel
    - CurrentInformation | Feratel
    - EventHeader | Feratel
    - EventHeaderShort | Feratel
    - GuestCardClassification | Feratel
    - InfrastructureLong | Feratel
    - InfrastructureOpeningTimes | Feratel
    - InfrastructurePriceInfo | Feratel
    - InfrastructureShort | Feratel
    - Package | Feratel
    - PackageContentLong | Feratel
    - PackageShortText | Feratel
    - ProductDescription | Feratel
    - SEOKeywords | Feratel
    - ShopItemDescription | Feratel
    - ServiceDescription | Feratel
    - ServiceProviderArrivalVoucher | Feratel
    - ServiceProviderConditions | Feratel
    - ServiceProviderDescription | Feratel
    - GTC | Feratel
    - hotel_important_information | Booking
    - hotel_description | Booking
    - intro | TIMM4
    - positionDescription | TIMM4
    - pricesDescription | TIMM4
    - keywords | TIMM4
    - culinarySpecialities | TIMM4
    - furtherSpecialities | TIMM4
    - dishes | TIMM4
    - barrierFreeDescription | TIMM4
    - restDays | TIMM4
    - companyHoliday | TIMM4
    - meetingPoint | TIMM4
    - timesComment | TIMM4

- POI - Kategorien | all:

- Rechte | all:

- MediaArchive - Tags | all:

- Gourmet-Bewertungen | all:

- Feratel - Veranstaltungstags | all:
    - $$Top-Event
    - $$Local
    - $$Town
    - $$Region
    - $$Subregion
    - $$Country

- Externer Status | all:
    - $$Aktiv
    - $$Inaktiv
    - $$Gelöscht

- Feratel - Status | all:
    - $$Aktiv
    - $$Inaktiv

- Feratel - Angebot - Status | all:
    - $$Buchbar
    - $$Nicht Buchbar

- Feratel - Preis - Typ | all:
    - $$Preis pro Person
    - $$Preis pro Package

- Feratel - Systeme | all:
    - $$Lokaler ExpertClient | L
    - $$Internet | T
    - $$Infomedia/Informator | I
    - $$Katalog | C
    - $$PIA | P

- OutdoorActive - Schwierigkeitsgrad | all:
    - $$unbekannt
    - $$leicht
    - $$mittel
    - $$schwierig

- OutdoorActive - Status | all:
    - $$geöffnet
    - $$geschlossen
    - $$Winteraktivität

- Länder | all:
    - Andorra
    - Dänemark
    - Deutschland
    - Frankreich
    - Italien
    - Kroatien
    - Liechtenstein
    - Österreich
    - Polen
    - Portugal
    - Slowakei
    - Slowenien
    - Schweiz
    - Schweden
    - Spanien
    - Tschechien
    - Ungarn

- Dateiformate | all:

- Ländercodes | show, edit, api, xml:
    - AF | Afghanistan
    - EG | Ägypten
    - AL | Albanien
    - DZ | Algerien
    - VI | Amerikanische Jungferninsel
    - UM | Amerikanische Überseeinseln, kleinere
    - AS | Amerikanisch-Samoa
    - AD | Andorra, Fürstentum
    - AO | Angola
    - AI | Anguilla
    - AG | Antigua und Barbuda
    - GQ | Äquatorialguinea
    - AR | Argentinien
    - AM | Armenien
    - AW | Aruba
    - AZ | Aserbaidschan
    - ET | Äthiopien
    - AU | Australien
    - BS | Bahamas
    - BH | Bahrain
    - BD | Bangladesch
    - BB | Barbados
    - BE | Belgien
    - BZ | Belize
    - BJ | Benin
    - BM | Bermudas
    - BT | Bhutan, Königreich
    - BO | Bolivien
    - BA | Bosnien-Herzegowina
    - BW | Botsuana
    - BV | Bouvetinseln
    - BR | Brasilien
    - VG | Britische Jungferninseln
    - IO | Britisches Territorium im Indischen Ozean
    - BN | Brunei Darussalam
    - BG | Bulgarien
    - YU | Bundesrepublik Yugoslawien
    - BF | Burkina Faso (ehem Obervolta)
    - BI | Burundi
    - CL | Chile
    - TW | China, Republik (Taiwan)
    - CN | China, Volksrepublik
    - CK | Cookinseln
    - CR | Costa Rica
    - DK | Dänemark
    - DE | Deutschland
    - DM | Dominica
    - DO | Dominikanische Republik
    - DJ | Dschibuti
    - EC | Ecuador
    - SV | El Salvador
    - CI | Elfenbeinküste (Cote dlvoire)
    - ER | Eritrea, Republik
    - EE | Estland
    - FK | Falkland Inseln (Islas Malvinas)
    - FO | Färöer
    - FJ | Fidschi
    - FI | Finnland
    - FR | Frankreich
    - TF | Französische Südgebiete
    - GF | Französisch-Guayana
    - PF | Französisch-Polynesien
    - GA | Gabun
    - GM | Gambia
    - GE | Georgien
    - GH | Ghana
    - GI | Gibraltar
    - GD | Grenada
    - GR | Griechenland
    - GL | Grönland
    - GP | Guadeloupe
    - GU | Guam
    - GT | Guatemala
    - GG | Guernsey
    - GN | Guinea
    - GW | Guinea-Bissau
    - GY | Guyana, Kooperative Republik
    - HT | Haiti
    - HM | Heart und McDonaldinseln
    - HN | Honduras
    - HK | Hongkong
    - IN | Indien
    - ID | Indonesien
    - IQ | Irak
    - IR | Iran, Islamische Republik
    - IE | Irland
    - IS | Island
    - IM | Isle of Man
    - IL | Israel
    - IT | Italien
    - JM | Jamaika
    - JP | Japan
    - YE | Jemen
    - JE | Jersey
    - JO | Jordanien
    - KY | Kaimaninseln
    - KH | Kambodscha
    - CM | Kamerun
    - CA | Kanada
    - CV | Kap Verde
    - KZ | Kasachstan
    - QA | Katar (Qatari)
    - KE | Kenia
    - KG | Kirgisistan
    - KI | Kiribati, Republik
    - CC | Kokosinseln
    - CO | Kolumbien
    - KM | Komoren, Islamische Bundesrepublik
    - CD | Kongo, Demokratische Republik (ehem Zaire)
    - ZR | Kongo, Demokratische Republik (ex-Zaire)
    - CG | Kongo, Republik
    - KP | Korea, Demokratische Volksrepublik
    - KR | Korea, Republik
    - RK | Kosovo
    - HR | Kroatien
    - CU | Kuba
    - KW | Kuwait
    - LA | Laos, Demokratische Volksrepublik
    - LS | Lesotho, Königreich
    - LV | Lettland
    - LB | Libanon
    - LR | Liberia
    - LY | Libysch-Arabische Volks-Jamahiria, Sozialistische
    - LI | Liechtenstein
    - LT | Litauen
    - LU | Luxemburg
    - MO | Macau (Aomen)
    - MG | Madagaskar
    - MW | Malawi
    - MY | Malaysia
    - MV | Malediven
    - ML | Mali
    - MT | Malta
    - MA | Marokko
    - MH | Marshallinseln, Republik der
    - MQ | Martinique
    - MR | Mauretanien
    - MU | Mauritius
    - YT | Mayotte
    - MK | Mazedonien (ehem jugoslawische Republik)
    - MX | Mexiko
    - FM | Mikronesien, Föderierte Staaten von
    - MC | Monaco
    - MN | Mongolei
    - MS | Montserrat
    - MZ | Mosambik
    - MM | Myanmar (ehem Birma / Burma)
    - NA | Namibia
    - NR | Nauru
    - NP | Nepal
    - NC | Neukaledonien
    - NZ | Neuseeland
    - NI | Nicaragua
    - NL | Niederlande
    - AN | Niederländische Antillen
    - NE | Niger
    - NG | Nigeria
    - NU | Niueinseln
    - MP | Nördliche Marianen, Commenwealth der
    - NF | Norfolkinseln
    - NO | Norwegen
    - OM | Oman
    - AT | Österreich
    - TP | Osttimor
    - PK | Pakistan
    - PS | Palästina
    - PW | Palau, Republik
    - PA | Panama
    - PG | Papua-Neuguinea
    - PY | Paraguay
    - PE | Peru
    - PH | Philippinen
    - PN | Pitcairninseln
    - PL | Polen
    - PT | Portugal
    - PR | Puerto Rico
    - MD | Republik, Moldau
    - ME | Republik Montenegro
    - RS | Republik Serbien
    - RW | Ruanda
    - RO | Rumänien
    - RU | Russische Föderation
    - SB | Salomonen
    - ZM | Sambia
    - WS | Samoa (Westsamoa)
    - ST | São Tomé und Principe, Demokratische Republik
    - SA | Saudi Arabien
    - SE | Schweden
    - CH | Schweiz
    - SN | Senegal
    - SC | Seychellen
    - SL | Sierra Leone
    - ZW | Simbabwe
    - SG | Singapur
    - SK | Slowakische Republik
    - SI | Slowenien
    - SO | Somalia
    - ES | Spanien
    - LK | Sri Lanka (ehem Ceylon)
    - SH | St. Helena
    - KN | St. Kitts und Nevis (ehem St. Christopher und Nevis)
    - LC | St. Lucia
    - SM | St. Marino
    - PM | St. Pierre und Miquelon
    - VC | St. Vincent und die Grenadinen
    - ZA | Südafrika
    - SD | Sudan, Republik
    - GS | Südgeorgien und die Sandwichinseln
    - SR | Suriname
    - SZ | Swasiland
    - SY | Syrien, Arabische Republik
    - TJ | Tadschikistan
    - TZ | Tansania
    - TH | Thailand
    - TG | Togo
    - TK | Tokelau
    - TO | Tonga, Königreich
    - TT | Trinidad und Tobago
    - TD | Tschad
    - CZ | Tschechische Republik
    - TN | Tunesien
    - TR | Türkei
    - TM | Turkmenistan
    - TC | Turks- und Caicosinseln
    - TV | Tuvalu
    - UG | Uganda
    - UA | Ukraine
    - HU | Ungarn
    - UY | Uruguay
    - UZ | Usbekistan
    - VU | Vanuatu
    - VA | Vatikanstadt
    - VE | Venezuela
    - AE | Vereinigte Arabische Emirate
    - US | Vereinigte Staaten von Amerika
    - GB | Vereinigtes Königreich Großbritannien
    - VN | Vietnam
    - WF | Wallis und Futuna
    - CX | Weihnachtsinseln
    - BY | Weißrußland (Belarus)
    - CF | Zentralafrikanische Republik
    - CY | Zypern

- Preis-Währung | all:
    - EUR | Euro
    - USD | US-Dollar
    - HUF | Ungarische Forint
    - CZK | Tschechische Kronen
    - HRK | Kroatische Kuna
    - CHF | Schweizer Franken
    - PLN | Polnische Złoty
    - DKK | Dänische Kronen

- Lizenzen | show, edit, api, xml:
    - Open Data:
        - Creative Commons:
            - Public Domain Mark **https://creativecommons.org/publicdomain/mark/1.0/
            - CC0 **https://creativecommons.org/publicdomain/zero/1.0/
            - CC BY:
                - CC BY 4.0 **https://creativecommons.org/licenses/by/4.0/
            - CC BY-SA:
                - CC BY-SA 4.0 **https://creativecommons.org/licenses/by-sa/4.0/
            - CC BY-ND:
                - CC BY-ND 4.0 **https://creativecommons.org/licenses/by-nd/4.0/
            - CC BY-NC:
                - CC BY-NC 4.0 **https://creativecommons.org/licenses/by-nc/4.0/
            - CC BY-NC-SA:
                - CC BY-NC-SA 4.0 **https://creativecommons.org/licenses/by-nc-sa/4.0/
            - CC BY-NC-ND:
                - CC BY-NC-ND 4.0 **https://creativecommons.org/licenses/by-nc-nd/4.0/
    - Sonstiges

- Veranstaltungsteilnahmemodus | all:
    - Teilnahme Online **https://pending.schema.org/OnlineEventAttendanceMode
    - Teilnahme Offline **https://pending.schema.org/OfflineEventAttendanceMode
    - Gemischte Teilnahme **https://pending.schema.org/MixedEventAttendanceMode

- Veranstaltungsstatus | all:
    - Veranstaltung abgesagt **https://schema.org/EventCancelled
    - zu Online-Veranstaltung umgewandelt **https://schema.org/EventMovedOnline
    - Veranstaltung auf unbekannten Zeitpunkt vertagt **https://schema.org/EventPostponed
    - Veranstaltung verschoben **https://schema.org/EventRescheduled
    - Veranstaltung geplant **https://schema.org/EventScheduled

- ActionTypes | all:
    - Download **https://schema.org/DownloadAction
    - externer Link **https://schema.org/ViewAction
    - Bestellen **https://schema.org/OrderAction

- ItemAvailability | all:
    - Eingestellt **https://schema.org/Discontinued
    - Verfügbar **https://schema.org/InStock
    - Nur im Geschäft **https://schema.org/InStoreOnly
    - Eingeschränkt verfügbar **https://schema.org/LimitedAvailability
    - Nur online **https://schema.org/OnlineOnly
    - Nicht vorrätig **https://schema.org/OutOfStock
    - Vorbestellen **https://schema.org/PreOrder
    - Vorverkauf **https://schema.org/PreSale
    - Ausverkauft **https://schema.org/SoldOut

- Preis - Kategorien | all:
