---
:skip_files:
  - app/models/data_cycle_core/generic/common/import_tags.rb
  - app/models/generic/rubbish/convert_to_md.rb
  - node_modules/
  - cache/
  - lib/data_cycle_core/rufus_yaml_scheduler.rb

:skip_checks:
  - CheckEOLRuby
